name: Json Rest Server
port: 8080
host: 192.168.1.67
database: database.json
#Indicates whether you want to start a socket server together with the rest server (true/false)
enableSocket: true
#Indicates the default socket access port (Websocket does not use this port): 8081
socketPort: 8081
broadcastProvider: socket
idType: uuid

auth:
  jwtSecret: cwsMXDtuP447WZQ63nM4dWZ3RppyMl
  jwtExpire: 3600
  urlSkip:
    - /images/:
        method: get
    - /users:
        method: post
    - /adm_users:
        method: post
